name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy-node:
    runs-on:
      - codebuild-github-action-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Cache Check - node_modules
        id: cache-check-nodemodules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      
      - name: NPM CI
        if: steps.cache-check-nodemodules.outputs.cache-hit != 'true'
        run: npm ci

      - name: Docker Setup
        uses: docker/setup-buildx-action@v3

      - name: ECR Setup
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 357491204644.dkr.ecr.us-east-1.amazonaws.com
      
      - name: Docker Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          cache-to: mode=max,image-manifest=true,oci-mediatypes=true,type=registry,ref=357491204644.dkr.ecr.us-east-1.amazonaws.com/nextjs:cache
          cache-from: 357491204644.dkr.ecr.us-east-1.amazonaws.com/nextjs:cache
          file: ./Dockerfile
          push: true
          tags: 357491204644.dkr.ecr.us-east-1.amazonaws.com/nextjs:cache
          