name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy-node:
    runs-on:
      - codebuild-github-action-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: NPM Install
        run: |
          npm install

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure Docker with ECR credentials
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 357491204644.dkr.ecr.us-east-1.amazonaws.com
          docker pull 357491204644.dkr.ecr.us-east-1.amazonaws.com/aml2023-nodejs:latest
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          cache-from: 357491204644.dkr.ecr.us-east-1.amazonaws.com/aml2023-nodejs:latest
          file: ./Dockerfile
          push: true
          tags: 357491204644.dkr.ecr.us-east-1.amazonaws.com/nextjs:${{ github.run_id }}