name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy-node:
    runs-on:
      - codebuild-github-action-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Cache Check - node_modules
        id: cache-check-nodemodules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      
      - name: NPM CI
        if: steps.cache-check-nodemodules.outputs.cache-hit != 'true'
        run: npm ci

      - run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 357491204644.dkr.ecr.us-east-1.amazonaws.com
          docker pull 357491204644.dkr.ecr.us-east-1.amazonaws.com/nextjs:latest || true
      - run: docker build --cache-from 357491204644.dkr.ecr.us-east-1.amazonaws.com/nextjs:latest -t 357491204644.dkr.ecr.us-east-1.amazonaws.com/nextjs:latest .
      #--cache-to mode=max,image-manifest=true,oci-mediatypes=true,type=registry,ref=357491204644.dkr.ecr.us-east-1.amazonaws.com/nextjs:cache
      - run: docker push 357491204644.dkr.ecr.us-east-1.amazonaws.com/nextjs:latest